name = "database-api"
compatibility_date = "2023-12-01"

[vars]
MONGO_URI = "mongodb+srv://jaysanjaykaria:zaLfLSpia4f1oYid@cluster1.mhnmkyu.mongodb.net/database-api?retryWrites=true&w=majority"
BEARER_TOKEN = "8B69D424748B6589A286FF7EC5939"